# List of git url paths which host terraform modules

org_name = "Bilak"


# MODULES
modules = [
  "Bilak-Terraform-Modules/terraform-azuread-group",
  "Bilak-Terraform-Modules/terraform-azurerm-aks",
  "Bilak-Terraform-Modules/terraform-azurerm-api-mgmt",
  "Bilak-Terraform-Modules/terraform-azurerm-api-mgmt-api",
  "Bilak-Terraform-Modules/terraform-azurerm-api-mgmt-api-diagnostics",
  "Bilak-Terraform-Modules/terraform-azurerm-api-mgmt-backend",
  "Bilak-Terraform-Modules/terraform-azurerm-app-configuration",
  "Bilak-Terraform-Modules/terraform-azurerm-app-service-plan",
  "Bilak-Terraform-Modules/terraform-azurerm-application-gw",
  "Bilak-Terraform-Modules/terraform-azurerm-application-insights",
  "Bilak-Terraform-Modules/terraform-azurerm-automation-acc",
  "Bilak-Terraform-Modules/terraform-azurerm-avd-vm",
  "Bilak-Terraform-Modules/terraform-azurerm-backup-vault",
  "Bilak-Terraform-Modules/terraform-azurerm-bastion",
  "Bilak-Terraform-Modules/terraform-azurerm-cognitive-services",
  "Bilak-Terraform-Modules/terraform-azurerm-container-app",
  "Bilak-Terraform-Modules/terraform-azurerm-container-instances",
  "Bilak-Terraform-Modules/terraform-azurerm-container-registry",
  "Bilak-Terraform-Modules/terraform-azurerm-cosmosdb",
  "Bilak-Terraform-Modules/terraform-azurerm-cost",
  "Bilak-Terraform-Modules/terraform-azurerm-databricks",
  "Bilak-Terraform-Modules/terraform-azurerm-datafactory",
  "Bilak-Terraform-Modules/terraform-azurerm-diagnostics",
  "Bilak-Terraform-Modules/terraform-azurerm-disk-encryption-set",
  "Bilak-Terraform-Modules/terraform-azurerm-eventhub",
  "Bilak-Terraform-Modules/terraform-azurerm-firewall",
  "Bilak-Terraform-Modules/terraform-azurerm-function-app-flex-consumption",
  "Bilak-Terraform-Modules/terraform-azurerm-ip-group",
  "Bilak-Terraform-Modules/terraform-azurerm-key-vault-key",          # Deprecated
  "Bilak-Terraform-Modules/terraform-azurerm-keyvault",
  "Bilak-Terraform-Modules/terraform-azurerm-keyvault-access-policy", # Deprecated
  "Bilak-Terraform-Modules/terraform-azurerm-keyvault-secret",        # Deprecated
  "Bilak-Terraform-Modules/terraform-azurerm-law",
  "Bilak-Terraform-Modules/terraform-azurerm-lb",
  "Bilak-Terraform-Modules/terraform-azurerm-linux-function-app",
  "Bilak-Terraform-Modules/terraform-azurerm-linux-web-app",
  "Bilak-Terraform-Modules/terraform-azurerm-logic-apps",
  "Bilak-Terraform-Modules/terraform-azurerm-managed-redis",
  "Bilak-Terraform-Modules/terraform-azurerm-monitor",
  "Bilak-Terraform-Modules/terraform-azurerm-mssql",
  "Bilak-Terraform-Modules/terraform-azurerm-nat-gateway",
  "Bilak-Terraform-Modules/terraform-azurerm-network-security-group",
  "Bilak-Terraform-Modules/terraform-azurerm-network-watcher",
  "Bilak-Terraform-Modules/terraform-azurerm-oracle-autonomous-database",
  "Bilak-Terraform-Modules/terraform-azurerm-pe",
  "Bilak-Terraform-Modules/terraform-azurerm-pim",
  "Bilak-Terraform-Modules/terraform-azurerm-policy-assignment",
  "Bilak-Terraform-Modules/terraform-azurerm-policy-definition",
  "Bilak-Terraform-Modules/terraform-azurerm-postgresql",
  "Bilak-Terraform-Modules/terraform-azurerm-private-dns-records",
  "Bilak-Terraform-Modules/terraform-azurerm-private-dns-zones",
  "Bilak-Terraform-Modules/terraform-azurerm-public-ip",
  "Bilak-Terraform-Modules/terraform-azurerm-rbac",
  "Bilak-Terraform-Modules/terraform-azurerm-recovery-services-vault",
  "Bilak-Terraform-Modules/terraform-azurerm-resource-group",
  "Bilak-Terraform-Modules/terraform-azurerm-route-table",
  "Bilak-Terraform-Modules/terraform-azurerm-search-service",
  "Bilak-Terraform-Modules/terraform-azurerm-service-bus",
  "Bilak-Terraform-Modules/terraform-azurerm-shared-image-gallery",
  "Bilak-Terraform-Modules/terraform-azurerm-static-web-app",
  "Bilak-Terraform-Modules/terraform-azurerm-storage-account",
  "Bilak-Terraform-Modules/terraform-azurerm-synapse-workspace",
  "Bilak-Terraform-Modules/terraform-azurerm-user-assigned-identity",
  "Bilak-Terraform-Modules/terraform-azurerm-virtual-desktop",
  "Bilak-Terraform-Modules/terraform-azurerm-virtual-machine-linux",
  "Bilak-Terraform-Modules/terraform-azurerm-virtual-machine-scale-set",
  "Bilak-Terraform-Modules/terraform-azurerm-virtual-machine-windows",
  "Bilak-Terraform-Modules/terraform-azurerm-virtual-network-gateway",
  "Bilak-Terraform-Modules/terraform-azurerm-virtual-network-peering",
  "Bilak-Terraform-Modules/terraform-azurerm-vnet",
  "Bilak-Terraform-Modules/terraform-azurerm-windows-function-app",
  "Bilak-Terraform-Modules/terraform-azurerm-windows-web-app"
]
